### PR TITLE
Download genhtml once

### LINKED ISSUE #96: Download genhtml once
Download genhtml only once

### PR DESCRIPTION
**Pull request by rhcu**
Fixes #96 

I've made it be downloaded in `latest_cov_build.py` with all other artifacts

### CODE REVIEW

**Comment by marco-c** [comment]
We should keep both the full report for the tests and the full report for the crawler, so we can see if there's something wrong in the diff.

**Comment by marco-c** [comment]
Maybe this will take too much space though, maybe let's just store the json files and then we can manually generate the html reports if we want to.

**Comment by rhcu** [comment]
It takes an additional 1.4 Gb (currently, the whole project with artifacts and `mozilla-central` takes ~5Gb). Ok, then I'll update the PR to download `genhtml` only once in `latest_cov_build.py` since it is done at every loop iteration for each website now.

**Comment by marco-c** [comment]
> Ok, then I'll update the PR to download genhtml only once in latest_cov_build.py since it is done at every loop iteration for each website now.

OK! And let's file an issue to keep the reports in json format.

**Pull request merged**
