### PR TITLE
Start lines from 1

### PR DESCRIPTION
**Pull request by rhcu**

### CODE REVIEW

**Comment by marco-c** [comment]
Does the problem only apply to simple line numbers or also to branch line numbers and function line numbers?

**Comment by rhcu** [comment]
I guess only to simple ones. I don't use enumerate in other cases: I forgot that by default it starts the count from 0.

**Comment by marco-c** [comment]
> I guess only to simple ones. I don't use enumerate in other cases: I forgot that by default it starts the count from 0.

Could you double check? You can look at a diff result, check if the function starts where it also starts in the linked mozilla-central file.

**Comment by rhcu** [comment]
Double checked functions = no problems there.

**Pull request merged**
